spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webflux_angular2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
  liquibase:
    url: jdbc:mysql://localhost:3306/webflux_angular2?createDatabaseIfNotExist=true
    user: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    default-schema: webflux_angular2
    change-log: classpath*:liquibase-outputChangeLog.xml
