spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webflux_angular2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    url: jdbc:mysql://localhost:3306/webflux_angular2?createDatabaseIfNotExist=true
    user: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    default-schema: webflux_angular2
    change-log: classpath:db/migration/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    database: mysql
